#!/bin/bash

alias cds='cd $HOME'
alias count='find . -type f | wc -l'
alias cpv='rsync -ah --info=progress2'  # Copy w/ progress bar

alias longhorn='ssh $USER@longhorn.tacc.utexas.edu'
alias theta='ssh $USER@theta.alcf.anl.gov'

export PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\W\[\033[00m\]\$ '
