"Auto install vim-plug
if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

"Load plugins
call plug#begin(expand('~/.vim/plugged'))
Plug 'itchyny/lightline.vim'
Plug 'arcticicestudio/nord-vim'
Plug 'joshdick/onedark.vim'
Plug 'ervandew/supertab'
Plug 'Yggdroot/indentLine'
Plug 'godlygeek/tabular'
Plug 'nathanaelkane/vim-indent-guides'
call plug#end()

syntax on

" onedark.vim override: Don't set a background color when running in a terminal;
" just use the terminal's background color
" `gui` is the hex color code used in GUI mode/nvim true-color mode
" `cterm` is the color code used in 256-color mode
" `cterm16` is the color code used in 16-color mode
if (has("autocmd") && !has("gui_running"))
  augroup colorset
    autocmd!
    let s:white = { "gui": "#ABB2BF", "cterm": "145", "cterm16" : "7" }
    autocmd ColorScheme * call onedark#set_highlight("Normal", { "fg": s:white }) " `bg` will not be styled since there is no `bg` setting
  augroup END
endif

colorscheme onedark

"set nocompatible
"if (has("termguicolors"))
"  set termguicolors
"endif

set background=dark
set hidden
set incsearch
set hlsearch
set nu     " line numbers
set cc=80  " ruler

"Show lightline statusbar
set laststatus=2
"Hide Vim -- INSERT --
set noshowmode

let g:onedark_terminal_italics=1
let g:nord_cursor_line_number_background=1
let g:nord_italic=1
let g:nord_italic_comments=1

let g:lightline = {
      \ 'colorscheme': 'onedark',
      \ }

" Use theme for indent line
let g:indentLine_setColors = 0
let g:indentLine_char = '▏'
" Use :IndentLinesToggle to enable
let g:indentLine_enabled = 0

" Use :IndentGuidesEnable
let g:indent_guides_enable_on_vim_startup = 0
let g:indent_guides_start_level = 2
let g:indent_guides_guide_size = 1
let g:indent_guides_auto_colors = 0
hi IndentGuidesOdd  ctermbg=DarkGrey
hi IndentGuidesEven ctermbg=DarkGrey

"OSX italic support workaround
let &t_ZH="\e[3m"
let &t_ZR="\e[23m"

"Make background transparent
"hi Normal guibg=NONE ctermbg=NONE
highlight Comment cterm=italic

set tabstop=4
set shiftwidth=4
set expandtab

" Python Specific Settings
au BufNewFile,BufRead *.py set tabstop=4 softtabstop=4 shiftwidth=4 textwidth=79 tw=0 
    \ fo-=t expandtab autoindent fileformat=unix

